In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
#Create a DataFrame
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
#Create an Instance of OneHotEncoding
encoder = OneHotEncoder()

In [8]:
##Perform fit and Transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [9]:
import pandas as pd
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [10]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [12]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [13]:
fit_Df = pd.read_csv('tips.csv')

In [14]:
fit_Df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
encoder_day = OneHotEncoder()

In [22]:
print(fit_Df.columns.tolist())

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

In [23]:
encoded_day = encoder_day.fit_transform(fit_Df[['day']]).toarray()

In [24]:
encoded_day_df = pd.DataFrame(encoded_day,columns=encoder_day.get_feature_names_out())

In [25]:
encoded_day_df

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [26]:
encoder_sex = OneHotEncoder()

In [27]:
encoded_sex = encoder_sex.fit_transform(fit_Df[['sex']]).toarray()

In [28]:
encoded_sex_df = pd.DataFrame(encoded_sex,columns=encoder_sex.get_feature_names_out())

In [29]:
encoded_sex_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [30]:
encoder_time = OneHotEncoder()

In [32]:
encoded_time = encoder_time.fit_transform(fit_Df[['time']]).toarray()

In [33]:
encoded_time_df = pd.DataFrame(encoded_time,columns=encoder_time.get_feature_names_out())

In [34]:
encoded_time_df

     time_Dinner  time_Lunch
0            1.0         0.0
1            1.0         0.0
2            1.0         0.0
3            1.0         0.0
4            1.0         0.0
..           ...         ...
239          1.0         0.0
240          1.0         0.0
241          1.0         0.0
242          1.0         0.0
243          1.0         0.0

[244 rows x 2 columns]